language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra
    
 deploy:
  provider: releases
  file: mediot.apk
  skip_cleanup: true
  on:
    tags: 
      all_branches: true
   jdk: oraclejdk8
   api_key:
    secure:  8a12ccfd0fbd13bfc89ce7c58a8d7d7e2c85c57d
    
    
    
